// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:040ed923-fb0b-4bbe-870e-d54ec09f2dc0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_8gqVLbLLT",
    "aws_user_pools_web_client_id": "35qklckjdl6pfibdt7kt2rkm8p"
};


export default awsmobile;
